Implementing step3
buildo/rps-mig pull request #2
Opened 2017-10-19 09:53 UTC by miguelpais

2017-10-19 09:55 UTC, miguelpais commented
@gabro A bit of magic going on in here with the implicit functions, not sure if it's the most standard way of having an implementation of a factory. 

It was kind of neat when we were going from Int to Move, but from Option[Int] to Move it's probably a bit ugly.

2017-10-19 12:54 UTC, gabro requested changes
Left some comments.

The overall idea is good, but you're missing one piece: try using the `None` case of the `Option` also to rule out any invalid move.

You want to validate, produce a `Option[Move]` and then keep on going only if the move is valid (return an error immediately otherwise).

2017-10-19 12:54 UTC, gabro commented on src/main/scala/rps/Game.scala
>        case (_, _) => "Invalid Round!!"
very minor, but you can simply use `case _ => ` here

2017-10-19 12:54 UTC, gabro commented on src/main/scala/rps/Game.scala
> +case object ROCK extends Move {
The convention is to use `Rock` instead of `ROCK`

2017-10-19 12:54 UTC, gabro commented on src/main/scala/rps/Game.scala
> +sealed abstract class Move {
No particular reason, but I'd rather use a `sealed trait` instead of a `sealed abstract class`. It's definitely more common.

2017-10-19 12:54 UTC, gabro commented on src/main/scala/rps/Game.scala
> +case object INVALID extends Move {
Let's not have an `Invalid` case.
Instead, when something is invalid, it should be `None`.

2017-10-19 12:54 UTC, gabro commented on src/main/scala/rps/Game.scala
> +  implicit def intToMove(move: Option[Int]): Move = {
don't make this implicit. There's little gain here and potentially some confusion.

2017-10-19 12:54 UTC, gabro commented on src/main/scala/rps/Game.scala
> +  implicit def intToMove(move: Option[Int]): Move = {
also ideally `intToMove` should take `Int` as an input as opposed to `Option[Int]`

2017-10-20 13:09 UTC, gabro approved these changes
👍 great!

2017-10-20 13:12 UTC, merged